### ISSUE TITLE
Rests not encoded

### ISSUE THREAD

**Issue by chrisdonahue** [czhuang/JSB-Chorales-dataset#1]
Thanks for this great resource.

The README says (of `Jsb16thSeparated.npz`) that "if a voice is silent at a given time step, its pitch is NaN". However, the arrays contained in this file are all int64 arrays and do not contain NaN pitches. Furthermore, none of the voices ever have any indication of a rest (all pitches are nonzero at all timesteps). Is there a file that has rest information encoded?

**Comment by jayelm** [comment]
Bump!

**Comment by cooijmanstim** [comment]
I took a look and it turns out that `Jsb16thSeparated.npz` contains a mix of int and float dtypes. Only the pieces that contain silences have float dtype (we relied on `numpy.savez_compressed` to figure it out, and it used int wherever it could get away with it). I've updated the file to have everything float16. You can iterate over the pieces and view the ones with silences like so:

```python
import numpy as np
import matplotlib.pyplot as plt

def show_piece(split, i, piece):
  top, bottom = int(np.nanmax(piece)), int(np.nanmin(piece))
  extent = top - bottom + 1

  nan_mask = np.isnan(piece)
  int_piece = np.where(nan_mask, top, np.round(piece).astype(int))

  pianoroll = np.eye(extent)[int_piece - bottom]
  assert pianoroll.shape == int_piece.shape + (extent,)
  pianoroll = np.where(nan_mask[..., None], 0, pianoroll)
  pianoroll = pianoroll.max(axis=1) # across voices

  plt.matshow(pianoroll.T, origin="lower", cmap="inferno")
  for t, i in zip(*np.nonzero(nan_mask)):
    print(t, i)
    plt.gca().axvline(t, color="blue")
  plt.show()

data = np.load("Jsb16thSeparated_float16.npz")
for split, pieces in data.items():
  for i, piece in enumerate(pieces):
    if np.isnan(piece).any():
      show_piece(split, i, piece)
```

**Comment by chrisdonahue** [comment]
THX TIM :D
